Sources/SymbolKit/SymbolGraph/Relationship.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/SymbolGraph/UnifiedSymbolGraph/GraphCollector.swift, Sources/SymbolKit/SymbolGraph/UnifiedSymbolGraph/UnifiedSymbol.swift, Sources/SymbolKit/SymbolGraph/UnifiedSymbolGraph/UnifiedSymbolGraph.swift, Tests/SymbolKitTests/Symbol/SymbolKindTests.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedSymbolTests.swift
This is the SymbolKit implementation of [this recent forums proposal](https://forums.swift.org/t/extending-swift-docc-to-support-objective-c-documentation/53243) to enable Objective-C support in Swift-DocC. This introduces the `UnifiedSymbolGraph`, `UnifiedSymbolGraph.Symbol`, and `GraphCollector` types that can be used to combine symbols and symbol graphs into a "unified" or "composite" symbol graph, that collects symbols together based on describing the same symbol or existing in the same module. These "unified symbol graph" types augment the existing symbol graph types by allowing a way to collect alternate versions of the same API. The existing `SymbolGraph` and `SymbolGraph.Symbol` types remain unchanged, and they can (and should!) still be used to decode symbol graphs from disk. …
=> add a unified symbol representation for cross-language symbol graphs

Sources/SymbolKit/SymbolGraph/Platform.swift, Tests/SymbolKitTests/SymbolGraph/PlatformTests.swift
'macos' is commonly used to identify macOS so we should allow it allongside 'macosx'.
Resolves rdar://85277688
=> Support 'macos' as a valid OS identifier

Tests/SymbolKitTests/SymbolGraph/PlatformTests.swift
It looks like #4 included a typo in one of the variable names in the tests. This slipped through when integrating in Swift-DocC, but running the SymbolKit tests locally causes a build failure.
=> fix variable name in PlatformTests

Sources/SymbolKit/SymbolGraph/LineList/LineList.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol+Snippet.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift
Snippets need a place to put the chunks of its code listing.
Chunks contain source code, and an optional source language and
name for a subheading at the minimum.
=> Add snippet mixin for symbols

openapi.yaml
Updates the OpenAPI spec that defines Symbol Graphs to include the `navigator` property that can optionally be included as part of `Symbol.Names`.
https://github.com/apple/swift-docc-symbolkit/blob/main/Sources/SymbolKit/SymbolGraph/Symbol/Symbol%2BNames.swift#L26
=> Add the `navigator` property of `Symbol.Names` to the spec

.github/pull_request_template.md, .gitignore, Package.swift, Package@swift-5.5.swift, README.md, Sources/SymbolKit/SymbolKit.docc/SymbolKit.md, bin/check-source, bin/test, bin/update-gh-pages-documentation-site
This sets the foundation for deploying Swift SymbolKit's documentation to GitHub pages.
- Adds the [Swift-DocC Plugin](https://github.com/apple/swift-docc-plugin) as a dependency of Swift-SymbolKit.
- Adds a script to simplify deployment of documentation to GitHub pages.
- Adds check-source and test script and fix missing headers.
- Update README docs (Remove some duplication and add a link to the github page).
- Adds pull request template file as other swift-docc related repo.
After merging this PR, we should be able to prepare a `gh-pages` branch on the main `swift-docc-symbolkit` repo with no content on it, run the `bin/update-gh-pages-documentation-site` script and have docs available.
None.
With Swift 5.6, run:
```
swift package --disable-sandbox preview-documentation --target …
```
=> Publish Swift SymbolKit's documentation to GitHub pages

Sources/SymbolKit/SymbolKit.docc/SymbolKit.md
Bug/issue #, if applicable: 
Swift code prefer 4 space indent instead 2 space indent.
Update SymbolKit.md's Swift demo code to 4 indent.
=> Update SymbolKit.md's Swift demo code to 4 indent

Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/SymbolKindTests.swift
Bug/issue #, if applicable: rdar://91166981
To allow SymbolKit to load symbol graphs from the in-progress Clang symbol-graph support (cf. https://reviews.llvm.org/D122611 and https://reviews.llvm.org/D122446), two new symbol kinds need to be added: One for C preprocessor macros, and one for Objective-C interface variables. This PR also adds a new test that ensures that all the `KindIdentifier` cases can parse back as themselves, to ensure that the `.init(identifier:)` and `lookupIdentifier()` functions don't get out of sync.
None
The "ExtractAPI" symbol graph support in Clang is still experimental, but symbol graphs can be found as part of [the ExtractAPI tests](https://github.com/llvm/llvm-project/tree/main/clang/test/ExtractAPI) in the LLVM main branch. Loading either the `macros.c` …
=> add `ivar` and `macro` to the known symbol kinds

Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/SymbolKindTests.swift
This is a cherry-pick of https://github.com/apple/swift-docc-symbolkit/pull/21 onto `release/5.7`.
**Explanation**: In preparation of allowing SymbolKit (and by proxy, Swift-DocC) to accept symbol graphs from Clang, this PR adds two new symbol kinds to the `KindIdentifier` enum: `ivar` (for Objective-C instance variables) and `macro` (for C preprocessor macros).
**Scope**: A low-impact change that shouldn't affect any existing uses of SymbolKit/Swift-DocC, and enables new ones.
**Radar**: rdar://91166981
**Risk**: Low. New `KindIdentifier` cases will not cause any existing workflows that use SymbolKit to change or be affected.
**Testing**: A new automated test has been added to ensure that symbol kinds can be parsed as themselves when serialized out and re-read. All existing automated …
=> [5.7] add `ivar` and `macro` to known symbol kinds

Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/SymbolKindTests.swift
Reverts apple/swift-docc-symbolkit#21
Adding new KindIdentifier cases apparently caused swift-docc to stop compiling, which is breaking CI in Swift. I'm reverting this for now so i can land it alongside the required DocC change.
=> Revert "add `ivar` and `macro` to the known symbol kinds"

Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/SymbolKindTests.swift
Reverts apple/swift-docc-symbolkit#23
The release/5.7 version of https://github.com/apple/swift-docc-symbolkit/pull/24. Reverting this so i can land it alongside the required swift-docc change.
=> Revert "[5.7] add `ivar` and `macro` to known symbol kinds"

Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/SymbolKindTests.swift
Reverts apple/swift-docc-symbolkit#25
This PR re-introduces #23, now that changes have landed in Swift-DocC (https://github.com/apple/swift-docc/pull/133) to allow it to land without breaking the build. The original PR's release information follows.
-----
**Explanation**: In preparation of allowing SymbolKit (and by proxy, Swift-DocC) to accept symbol graphs from Clang, this PR adds two new symbol kinds to the `KindIdentifier` enum: `ivar` (for Objective-C instance variables) and `macro` (for C preprocessor macros).
**Scope**: A low-impact change that shouldn't affect any existing uses of SymbolKit/Swift-DocC, and enables new ones.
**Radar**: rdar://91166981
**Risk**: Low. New `KindIdentifier` cases will not cause any existing workflows that use SymbolKit to change or be affected. …
=> Revert "Revert "[5.7] add `ivar` and `macro` to known symbol kinds""

Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/SymbolTests.swift
Cherry-pick of https://github.com/apple/swift-docc-symbolkit/pull/33
**Explanation**: This PR allows SymbolKit to be more resilient against malformed symbol graphs by dropping the Location mixin if it fails to decode.
**Scope**: Allows more symbol graphs to be accepted by SymbolKit by discarding incomplete information.
**Radar**: rdar://93797899
**Risk**: Very low. The Location mixin is optional to begin with, and clients like Swift-DocC are already capable of handling symbols without location information.
**Testing**: A new automated test has been added to ensure that a symbol graph with an incomplete Location mixin can still decode without throwing an exception. All existing automated tests still pass.
=> [5.7-04252022] drop the Location mixin if it's malformed

Sources/SymbolKit/SymbolGraph/Relationship/Relationship.swift, Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraphTests.swift
Cherry-pick of #28
**Explanation**: To allow Swift-DocC to better display language-specific documentation for symbols that differ across languages, this PR updates the `UnifiedSymbolGraph` to sort symbol relationships based on the selectors that they correspond to.
**Scope**: Affects consumers of the `UnifiedSymbolGraph`.
**Radar**: rdar://91246013
**Risk**: Low to medium. While source compatibility has been maintained by ensuring the catch-all `relationships` property is still available, corresponding updates to Swift-DocC (https://github.com/apple/swift-docc/pull/307) are required to fully make use of the new functionality.
**Testing**: New automated tests have been added to verify the new behavior. Existing automated tests still pass.
=> [5.7] separate relationships by the graph they came from

Sources/SymbolKit/SymbolGraph/Relationship/Relationship.swift, Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraphTests.swift
Bug/issue #, if applicable: rdar://91246013
This PR updates the `UnifiedSymbolGraph` to also differentiate relationships by a `Selector`. Since relationships don't have an `interfaceLanguage` of their own, their respective symbols are searched to supply one. They are first searched in the graph being processed, then in the in-progress unified graph as a whole. The latter step is intended to catch protocol conformance on an external type when it's being loaded from an extension symbol graph.
While the change was made in a way that preserved source compatibility, a corresponding change to Swift-DocC (https://github.com/apple/swift-docc/pull/304) is required to use the new information.
A new test case is added to verify the relationship sorting behavior in a basic case. As end-to-end …
=> separate relationships by the graph they came from

Sources/SymbolKit/SymbolGraph/LineList/LineList.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/SymbolTests.swift
Bug/issue #, if applicable: rdar://92185538
This decodes the new `module` and `uri` properties for `docComment` that were added in https://github.com/apple/swift/pull/58857
This data is only available with https://github.com/apple/swift/pull/58857 
These properties will be `nil` if the symbol graph doesn't contain the new information.
- Decode a symbol graph file that was created with a recent trunk toolchain. 
- Check that the symbol graph file contains "module" and "uri" fields for some documentation comments. 
- The decoded symbols should have source module name information and source file URL information. 
=> Decode the new docComment module and file information

Sources/SymbolKit/SymbolGraph/LineList/LineList.swift, Sources/SymbolKit/SymbolGraph/Symbol/Location.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/SymbolTests.swift
- **Rationale:** This is—together with the two other parts—fix an issue where documentation comments that are inherited from other modules may raise non-actionable warnings if the original documentation comment linked to other symbols in that module.
- **Risk:** Low
- **Risk Detail:** The improved method for checking the origin of a documentation comment is added as new API. 
- **Reward:** Medium
- **Reward Details:** Documentation builds successfully but documentation for protocol conformance symbols from other modules may render with broken links to symbols.
- **Original PR:** #42 
- **Issue:** rdar://92185538
- **Code Reviewed By:** @QuietMisdreavus 
- **Testing Details:** See https://github.com/apple/swift-docc/pull/314
=> [5.7] Decode the new docComment module and file information

Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraphTests.swift
Bug/issue #, if applicable: rdar://94736726 (not tagged in the commit since it will require a corresponding Swift-DocC PR)
Currently, we overwrite the `module.name` of a symbol graph in the `GraphCollector` when it looks like an extension symbol graph (i.e. a filename of `SomeModule@OtherModule.symbols.json`). However, this can cause a problem when the original module name is required to properly render symbols from the file (e.g. when it's a cross-import overlay and the module name is actually the name of the declaring module). Since Swift-DocC already handles the module name itself, this PR removes that behavior from SymbolKit so that that information can be made available to Swift-DocC.
Extension symbol graphs will still be unified with their extension module, as before, but the module …
=> don't update a symbol graph's module name if it's an extension

Sources/SymbolKit/SymbolGraph/Relationship/RelationshipKind.swift, Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Sources/SymbolKit/SymbolGraph/Symbol/Swift/Extension.swift, Tests/SymbolKitTests/SymbolGraph/SymbolTests.swift
Related to: apple/swift#59047, apple/swift-docc#210
This PR introduces the new `swift.extension` Symbol Kind and the  `extensionTo` Relationship Kind. In addition, it adds an optional `typeKind` field to the `Swift.Extension` Mixin.
These adaptions are necessary so that the `-emit-extension-block-symbols` format introduced in apple/swift#59047 can be parsed properly.
> **Warning** Since this PR adds the `extension` case to `SymbolGraph.Symbol.KindIdentifier`, this RP can break existing code.
apple/swift#59047
There is a new unit test for decoding `Swift.Extension`'s optional `typeKind` property.
The following files were produced with the `-emit-extension-block-symbols` mode from apple/swift#59047. Those and the old format should be decoded and re-encoded without errors or warnings. …
=> Adapt Symbol Graph Format to Changes Introduced in apple/swift#59047

Sources/SymbolKit/SymbolGraph/Module.swift, Sources/SymbolKit/SymbolGraph/OperatingSystem.swift, Sources/SymbolKit/SymbolGraph/Platform.swift, Sources/SymbolKit/SymbolGraph/Symbol/Snippet.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbol.swift, Tests/SymbolKitTests/SymbolGraph/ModuleTests.swift
SE-0356 latest changes include parsing "slices" out of snippets.
These are not quite the same as the current "chunks", which were
a speculation that eventually formed into "slices". Deprecate chunks
and add the slice data model.
Move snippet presentation code to a line-based format: slices are represented
simply as a name and index range to pull their code lines.
Add the `isVirtual` property to modules, for modules that are created
implicitly to hold relationships. When snippet symbol graphs are created,
a fake module is created to hold the snippets, since snippets do not come
from any one module. This property simplifies what is basically just a
heuristic in DocC to a simple factual check.
rdar://95220716
Required for related changes:
- https://github.com/apple/swift-docc/pull/338
- …
=> Add Slice to replace Snippet Chunks

Sources/SymbolKit/SymbolGraph/Module.swift, Sources/SymbolKit/SymbolGraph/OperatingSystem.swift, Sources/SymbolKit/SymbolGraph/Platform.swift, Sources/SymbolKit/SymbolGraph/Symbol/Snippet.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbol.swift, Tests/SymbolKitTests/SymbolGraph/ModuleTests.swift
**Explanation**: This changes the data model for Snippets to match latest changes to SE-0356 Swift Snippets, where "slices" were added to allow documentation authors to inline named regions of snippets instead of the whole snippet. This replaces the original design of "chunks" which was geared more towards "sub snippets".
**Scope**: This change is necessary to adopt slices in DocC and the DocC Plugin, so snippets are understood when found in Symbol Graphs, which is the data vehicle for snippet information.
**Risk**: This change should be low risk, since this makes changes to an optional mix-in to the JSON data and is only realized using the DocC Plugin and not Xcode.
**Testing**: 
- DocC itself (Swift)
- https://developer.apple.com/documentation/xcode/slothcreator_building_docc_documentati …
=> Add Slice to replace Snippet Chunks (#50)

Sources/SymbolKit/SymbolGraph/Symbol/FunctionSignature/FunctionSignature.swift, Sources/SymbolKit/SymbolGraph/Symbol/Swift/Extension.swift, Sources/SymbolKit/SymbolGraph/Symbol/Swift/Generics.swift
Some `Mixin`s were missing memberwise initializers. These are required for writing test-cases in apple/swift-docc#335.
None.
No testing required as change is trivial.
=> Add Missing Memberwise Initializers to Mixins

Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Tests/SymbolKitTests/UnifiedGraph/GraphCollectorTests.swift
This adaption is required to fix apple/swift-docc#210
Adds a strategy option to `GraphCollector`'s init. The `ExtensionGraphAssociation` option decides if extension graphs are merged with the extend**ing** or extend**ed** graph.
This PR does not introduce a breaking change and can be merged independently.
I added a new unit test to test the merging behavior for both ExtensionGraphAssociation options.
=> MergeStrategy with ExtensionGraphAssociation Option for GraphCollector

Sources/SymbolKit/Mixin/Mixin.swift, Sources/SymbolKit/SymbolGraph/AnyScalar.swift, Sources/SymbolKit/SymbolGraph/Relationship/RelationshipKind.swift, Sources/SymbolKit/SymbolGraph/Symbol/Availability/Availability.swift, Sources/SymbolKit/SymbolGraph/Symbol/DeclarationFragments/DeclarationFragments.swift, Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Sources/SymbolKit/SymbolGraph/Symbol/Mutability.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/SymbolGraph/Symbol/ValueConstraints.swift, Tests/SymbolKitTests/SymbolGraph/AnyScalarTests.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/ValueConstraintsTests.swift, bin/check-source
Bug/issue #, if applicable: rdar://101407961
I've been experimenting with REST API documentation support, and this PR adds models in support of describing JSON object structures for request/responses.
None.
N/A, this is not a user-facing change.
=> Add models for JSON dictionaries

Sources/SymbolKit/SymbolGraph/Symbol/HTTP/HTTP.swift, Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/HTTPTests.swift
Bug/issue #, if applicable: 
rdar://101408429
rdar://101409112
rdar://101408868
rdar://101408667
Add initial support for symbol graphs to model HTTP endpoints.
None.
See instructions in https://github.com/apple/swift-docc/pull/495
=> Add models for HTTP endpoints

Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/SymbolGraph/Symbol/ValueConstraints.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/ValueConstraintsTests.swift
Bug/issue #, if applicable: rdar://107432025
Add new `typeDetails` symbol mixin to hold type details of weakly-typed dictionary keys and HTTP parameters.
JSON structures and HTTP parameters can define fields that can take values of multiple types,
such as integers or strings. The `typeDetails` mixin allows the symbol graph to identify the individual types that are supported. DocC will use this information to list the "Possible types" in the rendered pages for the affected keys and parameters.
None.
To be described in parallel DocC PR.
=> Add new `typeDetails` symbol mixin

Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/SymbolGraph/Symbol/ValueConstraints.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/ValueConstraintsTests.swift
Cherry-pick of #56
- **Explanation**: HTTP/REST requests and JSON dictionaries can define parameters and keys that are weakly typed, allowing for multiple possible value types, such as integer or string. This extends symbol graphs to call out those individual allowed types and show up on the rendered page.
- **Scope**: Adds a new optional key to symbol graphs and converts that data to existing page structures used when rendering HTTP parameters and dictionary keys.
- **Radar**: rdar://107432025
- **Risk**: Low. Added key is optional.
- **Testing**: Changes are covered by unit tests.
- **Reviewer**: @QuietMisdreavus
=> [5.9] Add new `typeDetails` symbol mixin

Sources/SymbolKit/SymbolGraph/Relationship/ReferenceLocation.swift, Sources/SymbolKit/SymbolGraph/Relationship/Relationship.swift, Sources/SymbolKit/SymbolGraph/Relationship/RelationshipKind.swift, Tests/SymbolKitTests/SymbolGraph/Relationship/ReferenceLocationTests.swift
Bug/issue #, if applicable: rdar://108470705
This PR adds a new relationship kind, `references`, that describes a relationship where one symbol references another one in its implementation. It also introduces a `referenceLocation` mixin for relationships that describes the source range where the reference occurs.
The idea behind adding this information to a symbol graph would be to allow for more semantic analyses to be made on projects, for example to find unused symbols within a project. Including the source range also allows for a sort of "offline language server", by providing a data source for a "jump to definition" and "find references" functionality.
The JSON for these relationships would look like this:
```json
{
"kind": "references",
"source": "source",
"target": "target", …
```
=> add a "references" relationship kind and referenceLocation mixin

Sources/SymbolKit/SymbolGraph/Symbol/Swift/GenericConstraint.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/Swift/GenericConstraintTests.swift
Add a new initializer to SymbolGraph.Symbol.Swift.GenericConstraint that allows clients to create these structs directly in memory and not only from decoding JSON.
Swift DocC will use this to in the fix for rdar://112219546.
New unit tests were added. The Swift DocC test suite, which exercises this new code path, passes. Swift DocC was used to compile large frameworks without any new problems.
- [ x ] Added tests
- [ x ] Ran the `./bin/test` script and it succeeded
- ~~[ ] Updated documentation if necessary~~
=> Add a new initializer to GenericConstraint

Sources/SymbolKit/SymbolGraph/Symbol/AlternateDeclarations.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/SymbolGraph/SymbolGraph.swift, Tests/SymbolKitTests/SymbolGraph/SymbolGraphTests.swift
Bug/issue #, if applicable: rdar://111227476
When a symbol graph is decoded, SymbolKit currently deduplicates symbols with the same precise identifier by inspecting their declaration and discarding whichever symbol has an `async` keyword in its declaration fragments (or the shorter symbol if neither are async). However, this can lead to important information being lost. This PR adds a new mixin, `AlternateDeclarations`, that stores the declaration fragments of any symbol discarded in this "deduplication" process.
None
As this is a change in the internal data model, testing would need to be performed by decoding a symbol graph that contained "duplicate" symbols and re-encoding it to see the new `alternateDeclarations` mixin. An automated test has been added to ensure that the information …
=> add 'AlternateDeclarations' mixin

Sources/SymbolKit/Mixin/Mixin+Equals.swift, Sources/SymbolKit/Mixin/Mixin+Hash.swift, Sources/SymbolKit/Mixin/Mixin.swift, Sources/SymbolKit/SymbolGraph/Module.swift, Sources/SymbolKit/SymbolGraph/Relationship/Relationship.swift, Sources/SymbolKit/SymbolGraph/Symbol/Availability/Availability.swift, Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Sources/SymbolKit/SymbolKit.docc/GraphFormatExtensions.md, Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Tests/SymbolKitTests/SymbolGraph/Relationship/HashableTests.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/SymbolKindTests.swift, bin/check-source
Fix several typos in documentation. No code changes.
=> Fix typos in documentation.

Sources/SymbolKit/SymbolGraph/Symbol/DeclarationFragments/DeclarationFragments.swift, Sources/SymbolKit/SymbolGraph/Symbol/FunctionSignature/FunctionParameter.swift, Sources/SymbolKit/SymbolGraph/Symbol/FunctionSignature/FunctionSignature.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/FunctionSignatureTests.swift, openapi.yaml
Bug/issue #, if applicable: 
This surface both the external "argument name" and the internal "parameter name" for FunctionParameter values. 
The JSON key used for the internal name is "internalName", based on [what the Swift symbol graph extractor emits](https://github.com/apple/swift/blob/main/lib/SymbolGraphGen/Symbol.cpp#L422-L430).
With two different names to pick from, this updates the `name` property to behave as its documented:
> The name of the function parameter, as referred to in user code (must match the name used in the documentation comment).
Since it's the internal name that's used in user code and in the documentation comment, `name` returns `internalName`.
If the parameter has both an external "argument name" and an internal "parameter name", then `name` returns the …
=> Surface both external and internal names for FunctionParameter values 

Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift
Bug/issue #, if applicable: rdar://119722462
Clang's upcoming C++ support changed how C unions are represented in the symbol graph by giving them their own `union` symbol kind. This PR adds support for dedicated `union` symbols.
None
See instructions on the Swift-DocC PR: https://github.com/apple/swift-docc/pull/785
- [ n/a ] Added tests (symbol kind round-trip encoding is already tested in `SymbolKindTests.testKindIdentifierRoundTrip`)
- [ n/a ] Updated documentation if necessary
=> add support for 'union' symbols

Sources/SymbolKit/SymbolGraph/Symbol/Availability/Availability.swift, Sources/SymbolKit/SymbolGraph/SymbolGraph+Overloads.swift, Tests/SymbolKitTests/SymbolGraph/SymbolGraph+OverloadsTests.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraph+OverloadsTests.swift
Bug/issue #, if applicable: rdar://124164488
When combining overloaded symbols, we currently display whatever sorts first by declaration (or identifier in the absence of declarations) as the overload group symbol's template. This can create a problem in the end viewer if this symbol happens to be deprecated, since it will now appear as if the overload group as a whole is deprecated. This PR addresses this possibility by adjusting the overloads sorting algorithm to float non-deprecated symbols to the top of the sorted list.
None
Automated testing verifies the new behavior.
=> sort deprecated overloads below non-deprecated ones

Sources/SymbolKit/SymbolGraph/Symbol/Availability/Availability.swift, Sources/SymbolKit/SymbolGraph/SymbolGraph+Overloads.swift, Tests/SymbolKitTests/SymbolGraph/SymbolGraph+OverloadsTests.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraph+OverloadsTests.swift
- **Explanation**: Updates the overloads feature to preferentially sort non-deprecated overloads above deprecated ones.
- **Scope**: UX enhancement for an optional feature
- **Issue**: rdar://124164488
- **Original PR**: https://github.com/apple/swift-docc-symbolkit/pull/74
- **Risk**: Low. The code change is minor and is otherwise not exercised in normal circumstances.
- **Testing**: Automated testing has been added to ensure the new behavior.
- **Reviewer**: @d-ronnqvist
=> [6.0] sort deprecated overloads below non-deprecated ones

Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbol.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraph+OverloadsTests.swift
Bug/issue #, if applicable: rdar://128284906
In #72, i introduced a processing step for cross-platform overload groups where those groups were different depending on the symbol graph that they appeared in. However, this implementation had a flaw: When cleaning up relationships to superfluous overload groups, i used the overloads' "main graph selectors" to restrict which lists of relationships to iterate over. This meant that such overload groups that appeared in extension symbol graphs were not properly cleaned up, leading to a crash in Swift-DocC. This PR updates the filter to use a new `allSelectors` property, which allows these extension overloads to be handled correctly.
None
Automated testing verifies the expected behavior.
Make sure you check off the following items. If they cannot …
=> use all selectors, not just "main graph selectors", when collecting overloads-per-selector

Sources/SymbolKit/SymbolGraph/Symbol/PlistDetails.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/PlistDetailsTests.swift
Bug/issue #, if applicable: 131539008
Add support to property list details. `plistDetails` mixin created to store detail information about property list keys symbols.
N/A
https://github.com/sofiaromorales/swift-docc-symbolkit/blob/33e73bc63742bc7f2151eb3d504b6878a906b0f5/Tests/SymbolKitTests/SymbolGraph/Symbol/PlistDetailsTests.swift
=> Add support to property list keys details.

Sources/SymbolKit/SymbolGraph/Symbol/PlistDetails.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/Symbol/PlistDetailsTests.swift
**Explanation:** Adds`plistDetails` mixin created to store detail information about property list keys symbols.
**Scope:** New mixin to store optional data to document plist keys.
**Issue** :rdar://131539008
**Original PR:** https://github.com/swiftlang/swift-docc-symbolkit/pull/79
**Risk:** Low. 
**Testing**: Unit tests has been added to ensure the correct behavior.
**Reviewer:** @QuietMisdreavus
=>  Add support to property list details. (#79) [6.0]

Sources/SymbolKit/SymbolGraph/Platform.swift, Sources/SymbolKit/SymbolGraph/Symbol/Availability/Domain.swift, Tests/SymbolKitTests/SymbolGraph/PlatformTests.swift
Bug/issue #, if applicable: rdar://123091182
This PR adds a new parsed platform name, `visionOS`, that can be returned from the `SymbolGraph.Platform.name` property when a symbol graph with an operating system name of `visionos` is handled.
None
Automated testing has been extended to ensure that the platform name loads correctly.
- [ n/a ] Updated documentation if necessary
=> add visionOS as a valid platform name

Sources/SymbolKit/SymbolGraph/Symbol/DeclarationFragments/DeclarationFragments+Simplify.swift, Sources/SymbolKit/SymbolGraph/SymbolGraph+Overloads.swift, Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbol.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph+Overloads.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraph+OverloadsTests.swift
Bug/issue #, if applicable: rdar://131639487
This PR updates the unified symbol graph collector to optionally create overload groups separately from the previous iteration, where it combined pre-existing overload groups created on individual symbol graphs. To preserve API compatibility (and use outside of unified symbol graphs), the other mechanisms are preserved, but they suffer from a bug. When overloads are added in disjoint sets, whether from an extension or from alternate platforms, the old overload grouping code failed to combine them together. This updated code ensures that all overload groups reflect all of the available symbols, regardless of their source.
None
A companion PR on Swift-DocC will go more in-depth into testing. This PR contains additional automated tests that …
=> add a separate overload-group calculation in the unified graph collector

Sources/SymbolKit/SymbolGraph/Symbol/DeclarationFragments/DeclarationFragments+Simplify.swift, Sources/SymbolKit/SymbolGraph/SymbolGraph+Overloads.swift, Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbol.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph+Overloads.swift, Sources/SymbolKit/UnifiedSymbolGraph/UnifiedSymbolGraph.swift, Tests/SymbolKitTests/UnifiedGraph/UnifiedGraph+OverloadsTests.swift
Bug/issue #, if applicable: rdar://131639487
- **Explanation**: Adds an updated overload grouping calculation so that overloads from separate symbol graphs are correctly grouped.
- **Scope**: New optional branch in the unified graph collector, used by an optional feature in Swift-DocC.
- **Issue**: rdar://131639487
- **Original PR**: https://github.com/swiftlang/swift-docc-symbolkit/pull/81
- **Risk**: Low. The overloads feature is an experimental feature in Swift-DocC, and the code added here is an optional code path that is not taken in normal use.
- **Testing**: New automated tests demonstrate the bugs newly fixed; updated existing tests ensure that existing behavior is the same between the old and the new paths.
- **Reviewer**: @daniel-grumberg
=> [6.0] add a separate overload-group calculation in the unified graph collector

Sources/SymbolKit/SymbolGraph/Symbol/AlternateDeclarations.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift, Tests/SymbolKitTests/SymbolGraph/SymbolGraphTests.swift
Bug/issue #, if applicable: rdar://133767750
The "alternate declarations" mechanism added in https://github.com/swiftlang/swift-docc-symbolkit/pull/60 only preserves the declaration fragments of an alternate symbol, but this can hide other information, for example the related `functionSignature` mixin that is now used by Swift-DocC to lint documentation. This PR updates the "alternate declarations" functionality to save all of a symbol's mixins and its doc comment when merging alternate symbols together.
None
This is a purely API change, so coverage is handled with automated tests. A forthcoming PR on Swift-DocC will use the new API.
=> save mixins alongside declarations for symbol alternates

Sources/SymbolKit/SymbolGraph/SymbolGraph.swift, Tests/SymbolKitTests/SymbolGraph/SymbolGraphTests.swift
Bug/issue #, if applicable: rdar://138648876
In rare scenarios, it's possible for an Objective-C symbol to be imported into Swift with two names: One with a direct translation of the parameter names, and one with a modified symbol name. The former is imported with an obsolete availability marker, with a `renamed` key that points to the latter. SymbolKit's current selection behavior for symbol alternates chooses the original name, since the declaration is longer than the modified version. This leads to an obsolete symbol being represented in the decoded symbol graph, even though there is a non-obsolete declaration available for that symbol.
This PR updates the alternate symbol selection to prefer symbols that are not obsolete, deprecated, or unavailable.
None
Unfortunately, i could not …
=> don't use obsolete/deprecated/unavailable symbols as the main symbol

Sources/SymbolKit/SymbolGraph/SymbolGraph.swift, Tests/SymbolKitTests/SymbolGraph/SymbolGraphTests.swift
- **Explanation**: Updates the "alternate symbol" logic to handle rare occurrences where Objective-C symbols imported into Swift have an obsolete alternate that is currently selected as the primary symbol.
- **Scope**: Bug fix to handle an uncommon issue
- **Issues**: rdar://138648876
- **Original PRs**: https://github.com/swiftlang/swift-docc-symbolkit/pull/91
- **Risk**: Low. 
- **Testing**: New tests have been added to ensure the new functionality. Existing tests pass.
- **Reviewers**: @d-ronnqvist
=> [6.1] don't use obsolete/deprecated/unavailable symbols as the main symbol

Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Tests/SymbolKitTests/UnifiedGraph/GraphCollectorTests.swift
- expanded documentatin on mergeSymbolGraph to describe the forceLoading
parameter.
- updated the logic to use the lack of `@` and the `isVirtual` metadata
to determine if a symbolgraph is the primary graph for that module.
resolves #88 
Snippet extension graphs being considered `primary` is the source of non-deterministic results in previewing documentation that include snippets (https://github.com/swiftlang/swift-docc/issues/1084). For the logic within swift-dock's SymbolGraphLoader, they should be considered `extension` graphs. Since the snippet symbol graph extractor doesn't generate an `@` in the file name of the graph, the logic is amended to look at the isVirtual metadata for the module, which is set to `true` for snippets.
I considered using the name generated by the snippet …
=> adds support to correctly identify snippet symbolgraphs

Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Tests/SymbolKitTests/UnifiedGraph/GraphCollectorTests.swift
- expanded documentation on mergeSymbolGraph to describe the forceLoading
parameter.
- updated the logic to use the lack of @ and the isVirtual metadata
to determine if a symbolgraph is the primary graph for that module.
- resolves https://github.com/swiftlang/swift-docc-symbolkit/issues/88
Snippet extension graphs being considered primary is the source of non-deterministic results in previewing documentation that include snippets (https://github.com/swiftlang/swift-docc/issues/1084). For the logic within swift-dock's SymbolGraphLoader, they should be considered extension graphs. Since the snippet symbol graph extractor doesn't generate an @ in the file name of the graph, the logic is amended to look at the isVirtual metadata for the module, which is set to true for snippets.
I considered …
=> Support snippet symbolgraph

Sources/SymbolKit/SymbolGraph/Relationship/Relationship.swift, Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift
This fixes build failures for setups that have https://github.com/swiftlang/swift-foundation/pull/1169 but not https://github.com/swiftlang/swift/pull/79382.
rdar://145669600
=> Change type of `userInfo` to support `[CodingUserInfoKey: any Sendable]`

Sources/SymbolKit/SymbolGraph/SemanticVersion.swift, Tests/SymbolKitTests/SymbolGraph/LineList/SemanticVersionTests.swift, bin/check-source
Bug/issue #, if applicable: rdar://147937598
It turns out that the Swift symbol graph generator emits an integer field for the `prerelease` part of a version, if it's present. This causes a decoding error in SymbolKit, since it's expecting a string. This PR updates the `SemanticVersion` type to allow decoding JSON with either a string or an integer for the `prerelease` field.
None
This has been covered with automated tests.
- [ n/a ] Updated documentation if necessary
=> allow SemanticVersion prerelease field to be int or string

Sources/SymbolKit/SymbolGraph/Relationship/Relationship.swift, Sources/SymbolKit/SymbolGraph/Symbol/KindIdentifier.swift, Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift
Reverts swiftlang/swift-docc-symbolkit#96. 
All relevant setups that have https://github.com/swiftlang/swift-foundation/pull/1169 should have https://github.com/swiftlang/swift/pull/79382 by now.
=> Revert "Change type of `userInfo` to support `[CodingUserInfoKey: any Sendable]`"

Sources/SymbolKit/SymbolGraph/Symbol/Availability/Domain.swift
Bug/issue #, if applicable: None (though it is related to rdar://151390924)
https://github.com/swiftlang/swift/pull/81715 introduces a new availability domain `_SwiftToolchain`, that is rendered into symbol graphs with the token `SwiftToolchain`. This PR adds a new static property to `Availability.Domain` that can be used to compare the received value.
https://github.com/swiftlang/swift/pull/81715 (though they can be merged in any order)
Complete testing will need to happen with integration in Swift-DocC (in a forthcoming PR)
- [ n/a ] Added tests
=> add SwiftToolchain as a recognized availability domain

Sources/SymbolKit/UnifiedSymbolGraph/GraphCollector.swift, Tests/SymbolKitTests/UnifiedGraph/CrossImportOverlaySymbolGraphs.swift, Tests/SymbolKitTests/UnifiedGraph/GraphCollectorTests.swift
Follow up from https://github.com/swiftlang/swift-docc/pull/1091/files#r2298429213 to address missing logic to accommodate a symbol graph from a cross-import overlay. The additional logic isn't yet matched with tests that verify the results in a loading scenario
=> add logic to properly handle cross-import overlay graphs
